"""Domain enumerations and constants for Scopewatch."""

from enum import Enum


class RunStatus(str, Enum):
    ACTIVE = "ACTIVE"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class PolicyOutcome(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    HOLD = "HOLD"


class ReasonCode(str, Enum):
    ALLOWED_TOOL_AND_RESOURCE = "ALLOWED_TOOL_AND_RESOURCE"
    TOOL_NOT_ALLOWED = "TOOL_NOT_ALLOWED"
    OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    PATH_OUTSIDE_WORKSPACE = "PATH_OUTSIDE_WORKSPACE"
    PATH_NOT_ALLOWED = "PATH_NOT_ALLOWED"
    BLOCKED_PATH = "BLOCKED_PATH"
    PATH_TRAVERSAL = "PATH_TRAVERSAL"
    SYMLINK_ESCAPE = "SYMLINK_ESCAPE"
    NETWORK_DISABLED = "NETWORK_DISABLED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    MALFORMED_REQUEST = "MALFORMED_REQUEST"
    UNSUPPORTED_OPERATION = "UNSUPPORTED_OPERATION"
    POLICY_ERROR = "POLICY_ERROR"
    REASONING_SCOPE_CONCERN = "REASONING_SCOPE_CONCERN"
    REASONING_AUDIT_FAILED = "REASONING_AUDIT_FAILED"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    EXPIRED = "EXPIRED"
    CONSUMED = "CONSUMED"


class ExecutionStatus(str, Enum):
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
    NOT_EXECUTED = "NOT_EXECUTED"


class EventType(str, Enum):
    RUN_CREATED = "RUN_CREATED"
    ACTION_REQUESTED = "ACTION_REQUESTED"
    POLICY_ALLOWED = "POLICY_ALLOWED"
    POLICY_DENIED = "POLICY_DENIED"
    POLICY_HELD = "POLICY_HELD"
    APPROVAL_REQUESTED = "APPROVAL_REQUESTED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"
    APPROVAL_DENIED = "APPROVAL_DENIED"
    APPROVAL_EXPIRED = "APPROVAL_EXPIRED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    RUN_COMPLETED = "RUN_COMPLETED"
    SYSTEM_ERROR = "SYSTEM_ERROR"
    REASONING_AUDIT_COMPLETED = "REASONING_AUDIT_COMPLETED"
    REASONING_AUDIT_FAILED = "REASONING_AUDIT_FAILED"


class ReasoningProvenance(str, Enum):
    UNAVAILABLE = "UNAVAILABLE"
    AGENT_AUTHORED_SUMMARY = "AGENT_AUTHORED_SUMMARY"
    PROVIDER_EXPOSED_TRACE = "PROVIDER_EXPOSED_TRACE"
    SYNTHETIC_FIXTURE = "SYNTHETIC_FIXTURE"


SUPPORTED_TOOLS = {"workspace"}
SUPPORTED_OPERATIONS = {
    "list_directory",
    "read_text",
    "write_text",
    "delete_path",
    "network_request",
}
EXECUTABLE_OPERATIONS = {
    "list_directory",
    "read_text",
    "write_text",
}
